import { Eyebrow } from "@/components/section-heading";
import { Reveal } from "@/components/reveal";
import { CountUp } from "@/components/count-up";
import { cn } from "@/lib/utils";

/**
 * What Assay checks — evidence for the argument made above it, not the pitch.
 *
 * This was a six-column bento of identical cards, each with an icon in a
 * rounded square, a mono label, a title and a body. That is the single most
 * recognisable "generated by an AI website builder" pattern there is, and our
 * users build with the exact tools that emit it.
 *
 * What replaced it: the checks are text, and the only cards left are the two
 * that hold real evidence — the table readout and the leaked key. A card should
 * mean "this is a thing you could look at", not "this is a paragraph".
 *
 * The layout is also deliberately asymmetric. Every other section on the page
 * is a centred or single-measure column; giving one section a real two-column
 * break stops the page reading as one long stack.
 */
const TABLES = [
  { text: "profiles — open to the public", held: true },
  { text: "orders — open to the public", held: true },
  { text: "messages — protected", held: false },
];

const CHECKS = [
  {
    label: "Exposed secrets",
    body: "Secret keys, Stripe keys and tokens hiding in the JavaScript your app ships — found and flagged, never stored.",
    evidence: (
      <p className="rounded-[var(--radius-control)] border border-oxblood/40 bg-oxblood/5 px-3 py-2.5 font-mono text-xs text-oxblood-soft">
        sk_live_••••••••••••&nbsp;&nbsp;exposed
      </p>
    ),
  },
  {
    label: "Safety score",
    body: "Every finding rolls up into one number, worst issues first, so you know what to do before you know what it means.",
    evidence: (
      <p className="flex items-baseline gap-2">
        <CountUp to={92} className="font-display text-4xl font-bold text-ivory" />
        <span className="font-mono text-xs uppercase tracking-[0.16em] text-ash">
          / 100
        </span>
      </p>
    ),
  },
  {
    // Was "The verdict", showing both hallmark stamps. The section below this
    // one is the verdict, at full size, with a real report in it — so this
    // column was a thumbnail of the next scroll. Replaced with the check that
    // actually runs and appeared nowhere on the page.
    label: "Missing protections",
    body: "The response headers a published app is meant to send and a generated one usually doesn't — the difference between a bug and a breach.",
    evidence: (
      <p className="rounded-[var(--radius-control)] border border-line bg-onyx px-3 py-2.5 font-mono text-xs text-ivory-dim">
        content-security-policy&nbsp;&nbsp;
        <span className="text-oxblood-soft">absent</span>
      </p>
    ),
  },
];

export function FeatureBento() {
  return (
    <section className="edge-b relative overflow-hidden">
      <div className="relative mx-auto w-full max-w-6xl px-4 py-16 sm:px-6 xl:max-w-7xl xl:py-24">
        <Reveal>
          <Eyebrow label="What it checks" />
          <h2 className="mt-5 max-w-2xl text-balance font-display text-2xl font-bold leading-[1.1] tracking-[-0.02em] text-ivory sm:text-[2rem] xl:text-[2.4rem]">
            The holes vibe-coded apps ship with, then one honest mark.
          </h2>
          <p className="mt-4 max-w-xl text-base leading-relaxed text-ivory-dim">
            An outside opinion is only worth having if it&rsquo;s a real one.
            Here&rsquo;s what Assay actually looks at, from outside your app,
            with no login and no access to your code.
          </p>
        </Reveal>

        {/* The one failure worth the room, and the one card worth having. */}
        <Reveal delay={90}>
          <div className="mt-12 grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-16 [&>*]:min-w-0">
            <div>
              <h3 className="font-display text-xl font-bold tracking-[-0.015em] text-ivory">
                An open database
              </h3>
              <p className="mt-3 max-w-md text-sm leading-relaxed text-ivory-dim">
                The most common vibe-coding failure: Supabase row-level security
                left off, so anyone can read — or change — every user&rsquo;s
                data. Assay probes it the safe, read-only way and tells you
                exactly what&rsquo;s reachable.
              </p>
            </div>

            <div className="overflow-hidden rounded-[var(--radius-card)] border border-line bg-onyx">
              <div className="border-b border-line px-4 py-2 font-mono text-xs text-ash">
                your tables
              </div>
              <ul className="divide-y divide-line/70">
                {TABLES.map((r) => (
                  <li
                    key={r.text}
                    className="flex items-center justify-between gap-3 px-4 py-2.5 font-mono text-xs"
                  >
                    <span className="text-ivory-dim">{r.text}</span>
                    <span
                      className={cn(
                        "text-[10px] uppercase tracking-[0.16em]",
                        r.held ? "text-oxblood-soft" : "text-ivory-dim",
                      )}
                    >
                      {r.held ? "exposed" : "ok"}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Reveal>

        {/* The rest are checks, not products. Rules, not cards. */}
        <Reveal delay={140}>
          <ul className="mt-12 grid gap-y-10 md:grid-cols-3 md:gap-x-12">
            {CHECKS.map((c) => (
              <li
                key={c.label}
                className="border-t border-line pt-6 md:border-t-0 md:border-l md:pl-8 md:pt-0 md:first:border-l-0 md:first:pl-0"
              >
                <h3 className="font-display text-xl font-bold tracking-[-0.015em] text-ivory">
                  {c.label}
                </h3>
                <p className="mt-3 max-w-sm text-sm leading-relaxed text-ivory-dim">
                  {c.body}
                </p>
                <div className="mt-5">{c.evidence}</div>
              </li>
            ))}
          </ul>
        </Reveal>
      </div>
    </section>
  );
}
